name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug: List Files in Working Directory
        run: |
          ls -la $GITHUB_WORKSPACE
          pwd

      - name: Install Dependencies
        run: npm install
        working-directory: $GITHUB_WORKSPACE/CodeDays/ # Correct relative path

      - name: Debug: List Files in Build Directory
        run: ls -la $GITHUB_WORKSPACE/CodeDays/
      
      - name: Build
        run: npm run build # Modify with your actual build command
        working-directory: $GITHUB_WORKSPACE/CodeDays/ # Correct relative path

      - name: Push Build
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: dist # Modify to match the output directory of your build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
